version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE_URL: http://172.28.92.57:6001/api
    container_name: coupa_frontend_testing
    ports:
      - "8080:80"
      - "8443:443"
    restart: unless-stopped
    networks:
      - coupa_network

networks:
  coupa_network:
    driver: bridge

